fix : null (null) has no keys

diff --git a/.github/workflows/test-pr.yaml b/.github/workflows/test-pr.yaml
--- a/.github/workflows/test-pr.yaml
+++ b/.github/workflows/test-pr.yaml
@@ -72,22 +72,28 @@ jobs:
         run: |
           set -e
           cd src/${{ matrix.templates }}
-          options=( $(jq -r '.options | keys[]' devcontainer-template.json) )
 
-          if [ "${options[0]}" != "" ] && [ "${options[0]}" != "null" ] ; then  
-            for option in "${options[@]}"
-            do
-              option_key="\${templateOption:$option}"
-              option_value=$(jq -r ".options | .${option} | .default" devcontainer-template.json)
+          # Configure templates only if `devcontainer-template.json` contains the `options` property.
+          optionProp=( $(jq -r '.options' devcontainer-template.json) )
 
-              if [ "${option_value}" = "" ] || [ "${option_value}" = "null" ] ; then  
-                echo "Template '${{ matrix.templates }}' is missing a default value for option '${option}'"
-                exit 1
-              fi
+          if [ "${optionProp}" != "" ] && [ "${optionProp}" != "null" ] ; then  
+            options=( $(jq -r '.options | keys[]' devcontainer-template.json) )
 
-              option_value_escaped=$(sed -e 's/[]\/$*.^[]/\\&/g' <<<"${option_value}")
-              find ./ -type f -print0 | xargs -0 sed -i "s/${option_key}/${option_value_escaped}/g"
-            done
+            if [ "${options[0]}" != "" ] && [ "${options[0]}" != "null" ] ; then  
+              for option in "${options[@]}"
+              do
+                option_key="\${templateOption:$option}"
+                option_value=$(jq -r ".options | .${option} | .default" devcontainer-template.json)
+
+                if [ "${option_value}" = "" ] || [ "${option_value}" = "null" ] ; then  
+                  echo "Template '${{ matrix.templates }}' is missing a default value for option '${option}'"
+                  exit 1
+                fi
+
+                option_value_escaped=$(sed -e 's/[]\/$*.^[]/\\&/g' <<<"${option_value}")
+                find ./ -type f -print0 | xargs -0 sed -i "s/${option_key}/${option_value_escaped}/g"
+              done
+            fi
           fi
 
       - name: Run Smoke Test
