fix indentations

diff --git a/.github/workflows/test-pr.yaml b/.github/workflows/test-pr.yaml
--- a/.github/workflows/test-pr.yaml
+++ b/.github/workflows/test-pr.yaml
@@ -4,112 +4,112 @@ on:
 
 jobs:
   detect-changes:
-  runs-on: ubuntu-latest
-  outputs:
-  templates: ${{ steps.filter.outputs.changes }}
-  steps:
-  - uses: dorny/paths-filter@v2
-    id: filter
-    with:
-    filters: |
-      alpine: ./**/alpine/**
-      anaconda: ./**/anaconda/**
-      anaconda-postgres: ./**/anaconda-postgres/**
-      cpp: ./**/cpp/**
-      cpp-mariadb: ./**/cpp-mariadb/**
-      debian: ./**/debian/**
-      docker-from-docker: ./**/docker-from-docker/**
-      docker-from-docker-compose: ./**/docker-from-docker-compose/**
-      docker-in-docker: ./**/docker-in-docker/**
-      dotnet: ./**/dotnet/**
-      dotnet-fsharp: ./**/dotnet-fsharp/**
-      dotnet-mssql: ./**/dotnet-mssql/**
-      dotnet-postgres: ./**/dotnet-postgres/**
-      go: ./**/go/**
-      go-postgres: ./**/go-postgres/**
-      java: ./**/java/**
-      java-8: ./**/java-8/**
-      java-postgres: ./**/java-postgres/**
-      javascript-node: ./**/javascript-node/**
-      javascript-node-mongo: ./**/javascript-node-mongo/**
-      javascript-node-postgres: ./**/javascript-node-postgres/**
-      jekyll: ./**/jekyll/**
-      kubernetes-helm: ./**/kubernetes-helm/**
-      kubernetes-helm-minikube: ./**/kubernetes-helm-minikube/**
-      markdown: ./**/markdown/**
-      miniconda: ./**/miniconda/**
-      miniconda-postgres: ./**/miniconda-postgres/**
-      php: ./**/php/**
-      php-mariadb: ./**/php-mariadb/**
-      postgres: ./**/postgres/**
-      powershell: ./**/powershell/**
-      python: ./**/python/**
-      ruby: ./**/ruby/**
-      ruby-rails-postgres: ./**/ruby-rails-postgres/**
-      rust: ./**/rust/**
-      rust-postgres: ./**/rust-postgres/**
-      typescript-node: ./**/typescript-node/**
-      ubuntu: ./**/ubuntu/**
-      universal: ./**/universal/**
+    runs-on: ubuntu-latest
+    outputs:
+      templates: ${{ steps.filter.outputs.changes }}
+    steps:
+      - uses: dorny/paths-filter@v2
+        id: filter
+        with:
+        filters: |
+          alpine: ./**/alpine/**
+          anaconda: ./**/anaconda/**
+          anaconda-postgres: ./**/anaconda-postgres/**
+          cpp: ./**/cpp/**
+          cpp-mariadb: ./**/cpp-mariadb/**
+          debian: ./**/debian/**
+          docker-from-docker: ./**/docker-from-docker/**
+          docker-from-docker-compose: ./**/docker-from-docker-compose/**
+          docker-in-docker: ./**/docker-in-docker/**
+          dotnet: ./**/dotnet/**
+          dotnet-fsharp: ./**/dotnet-fsharp/**
+          dotnet-mssql: ./**/dotnet-mssql/**
+          dotnet-postgres: ./**/dotnet-postgres/**
+          go: ./**/go/**
+          go-postgres: ./**/go-postgres/**
+          java: ./**/java/**
+          java-8: ./**/java-8/**
+          java-postgres: ./**/java-postgres/**
+          javascript-node: ./**/javascript-node/**
+          javascript-node-mongo: ./**/javascript-node-mongo/**
+          javascript-node-postgres: ./**/javascript-node-postgres/**
+          jekyll: ./**/jekyll/**
+          kubernetes-helm: ./**/kubernetes-helm/**
+          kubernetes-helm-minikube: ./**/kubernetes-helm-minikube/**
+          markdown: ./**/markdown/**
+          miniconda: ./**/miniconda/**
+          miniconda-postgres: ./**/miniconda-postgres/**
+          php: ./**/php/**
+          php-mariadb: ./**/php-mariadb/**
+          postgres: ./**/postgres/**
+          powershell: ./**/powershell/**
+          python: ./**/python/**
+          ruby: ./**/ruby/**
+          ruby-rails-postgres: ./**/ruby-rails-postgres/**
+          rust: ./**/rust/**
+          rust-postgres: ./**/rust-postgres/**
+          typescript-node: ./**/typescript-node/**
+          ubuntu: ./**/ubuntu/**
+          universal: ./**/universal/**
 
   test:
-  needs: [detect-changes]
-  runs-on: ubuntu-latest
-  continue-on-error: true
-  strategy:
-  matrix:
-    templates: ${{ fromJSON(needs.detect-changes.outputs.templates) }}
-  steps:
-  - uses: actions/checkout@v2
+    needs: [detect-changes]
+    runs-on: ubuntu-latest
+    continue-on-error: true
+    strategy:
+      matrix:
+        templates: ${{ fromJSON(needs.detect-changes.outputs.templates) }}
+    steps:
+      - uses: actions/checkout@v2
 
-  - name: "Install latest devcontainer CLI"
-    run: npm install -g @devcontainers/cli
+      - name: "Install latest devcontainer CLI"
+        run: npm install -g @devcontainers/cli
 
-  - name: "Generating tests for '${{ matrix.templates }}'"
-    run: echo "${{ matrix.templates }}"
+      - name: "Generating tests for '${{ matrix.templates }}'"
+        run: echo "${{ matrix.templates }}"
 
-  - name: Configure template
-    run: |
-      set -e
-      cd src/${{ matrix.templates }}
-      options=( $(jq -r '.options | keys[]' devcontainer-template.json) )
+      - name: Configure template
+        run: |
+          set -e
+          cd src/${{ matrix.templates }}
+          options=( $(jq -r '.options | keys[]' devcontainer-template.json) )
 
-      if [ "${options[0]}" != "" ] && [ "${options[0]}" != "null" ] ; then  
-        for option in "${options[@]}"
-        do
-          option_key="\${templateOption:$option}"
-          option_value=$(jq -r ".options | .${option} | .default" devcontainer-template.json)
+          if [ "${options[0]}" != "" ] && [ "${options[0]}" != "null" ] ; then  
+            for option in "${options[@]}"
+            do
+              option_key="\${templateOption:$option}"
+              option_value=$(jq -r ".options | .${option} | .default" devcontainer-template.json)
 
-          if [ "${option_value}" = "" ] || [ "${option_value}" = "null" ] ; then  
-            echo "Template '${{ matrix.templates }}' is missing a default value for option '${option}'"
+              if [ "${option_value}" = "" ] || [ "${option_value}" = "null" ] ; then  
+                echo "Template '${{ matrix.templates }}' is missing a default value for option '${option}'"
+                exit 1
+              fi
+
+              option_value_escaped=$(sed -e 's/[]\/$*.^[]/\\&/g' <<<"${option_value}")
+              find ./ -type f -print0 | xargs -0 sed -i "s/${option_key}/${option_value_escaped}/g"
+            done
+          fi
+
+      - name: Run Smoke Test
+        run: |
+          template_id="${{ matrix.templates }}"
+          src_dir="test/${template_id}"
+
+          if [ ! -d "$(pwd)/${src_dir}" ] ; then  
+            echo "Template '${{ matrix.templates }}' is missing a test folder"
             exit 1
           fi
 
-          option_value_escaped=$(sed -e 's/[]\/$*.^[]/\\&/g' <<<"${option_value}")
-          find ./ -type f -print0 | xargs -0 sed -i "s/${option_key}/${option_value_escaped}/g"
-        done
-      fi
+          dest_dir="src/${template_id}/test-project"
+          mkdir -p ${dest_dir}
+          cp -R ${src_dir}/* ${dest_dir}
 
-  - name: Run Smoke Test
-    run: |
-      template_id="${{ matrix.templates }}"
-      src_dir="test/${template_id}"
+          echo "Building dev container"
+          id_label="test-container=${template_id}"
+          devcontainer up --id-label ${id_label} --workspace-folder "src/${template_id}/"
 
-      if [ ! -d "$(pwd)/${src_dir}" ] ; then  
-        echo "Template '${{ matrix.templates }}' is missing a test folder"
-        exit 1
-      fi
+          echo "Running Smoke Test"
+          devcontainer exec --workspace-folder "src/${template_id}/" --id-label ${id_label} /bin/sh -c 'set -e && if [ -f "test-project/test.sh" ]; then cd test-project && if [ "$(id -u)" = "0" ]; then chmod +x test.sh; else sudo chmod +x test.sh; fi && ./test.sh; else ls -a; fi'
 
-      dest_dir="src/${template_id}/test-project"
-      mkdir -p ${dest_dir}
-      cp -R ${src_dir}/* ${dest_dir}
-
-      echo "Building dev container"
-      id_label="test-container=${template_id}"
-      devcontainer up --id-label ${id_label} --workspace-folder "src/${template_id}/"
-
-      echo "Running Smoke Test"
-      devcontainer exec --workspace-folder "src/${template_id}/" --id-label ${id_label} /bin/sh -c 'set -e && if [ -f "test-project/test.sh" ]; then cd test-project && if [ "$(id -u)" = "0" ]; then chmod +x test.sh; else sudo chmod +x test.sh; fi && ./test.sh; else ls -a; fi'
-
-      # Clean up
-      docker rm -f $(docker container ls -f "label=${id_label}" -q)
+          # Clean up
+          docker rm -f $(docker container ls -f "label=${id_label}" -q)
